version: 2
jobs:
  build_python_27:
    branches:

    only:
      - master
      - CItest

    machine: true

    environment:
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8


    steps:
      - checkout

      - restore_cache:
          key: miniconda-{{ .Branch }}

      - run:
          name: install miniconda
          command: |
           bash ./.circleci/install_conda.sh

      - save_cache:
          key: miniconda-{{ .Branch }}
          paths:
            - /home/circleci/miniconda

      - run:
          name: Build
          command: |
            source ~/miniconda/bin/activate root
            conda create -n CosmAna python=2.7
            source activate CosmAna
            conda install --file requirements.txt
            python setup.py build
            python setup.py install

      - run:
          name: Test
          command: |
            source ~/miniconda/bin/activate CosmAna
            cd tests && python runtests.py
            
      - run:
          name: MpiTest
          command: |
            source ~/miniconda/bin/activate CosmAna
            cd tests && mpirun -np 4 python runtests.py
            

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_python_27
